# version: "3.9"

services:
  backend:
    image: rutvikprajapati/skin-cancer-detection-backend:latest
    # build: ./backend
    container_name: skin-backend
    ports:
      - "8000:8000"
    volumes:
      - skin_data:/app
    restart: always

  frontend:
    image: rutvikprajapati/skin-cancer-detection-frontend:latest
    # build: ./frontend
    container_name: skin-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  skin_data: